# {
#     "hostPorts": [
#         {
#             "startPointHost":"127.0.0.1",
#             "startPointPort":1794,
#             "endPointHost":"127.0.0.1",
#             "endPointPort":22
#         },
#         {
#             "startPointHost":"127.0.0.1",
#             "startPointPort":1795,
#             "endPointHost":"127.0.0.1",
#             "endPointPort":80
#         }
#     ]
# }
uid: 12a3717ee3d3d2ba2a2229dbc204b99ba5da744e70db184e021e15dcc0a44554
hostPorts:
    -   startPointHost: "127.0.0.1"
        startPointPort: 1794
        endPointHost: "127.0.0.1"
        endPointPort: 22

    -   startPointHost: "127.0.0.1"
        startPointPort: 1795
        endPointHost: "127.0.0.1"
        endPointPort: 80