# {
#     "hostPorts": [
#         {
#             "startPointHost":"127.0.0.1",
#             "startPointPort":1794,
#             "endPointHost":"127.0.0.1",
#             "endPointPort":22
#         },
#         {
#             "startPointHost":"127.0.0.1",
#             "startPointPort":1795,
#             "endPointHost":"127.0.0.1",
#             "endPointPort":80
#         }
#     ]
# }

hostPorts:
    -   startPointHost: "127.0.0.1"
        startPointPort: 1794
        endPointHost: "127.0.0.1"
        endPointPort: 22

    -   startPointHost: "127.0.0.1"
        startPointPort: 1795
        endPointHost: "127.0.0.1"
        endPointPort: 80