// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payloads.proto

package payloads

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WebSocketPacketPayload struct {
	PacketType           uint32   `protobuf:"varint,1,opt,name=packet_type,json=packetType,proto3" json:"packet_type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	EHost                uint32   `protobuf:"varint,3,opt,name=e_host,json=eHost,proto3" json:"e_host,omitempty"`
	EPort                uint32   `protobuf:"varint,4,opt,name=e_port,json=ePort,proto3" json:"e_port,omitempty"`
	SHost                uint32   `protobuf:"varint,5,opt,name=s_host,json=sHost,proto3" json:"s_host,omitempty"`
	SPort                uint32   `protobuf:"varint,6,opt,name=s_port,json=sPort,proto3" json:"s_port,omitempty"`
	ConnectionId         []byte   `protobuf:"bytes,7,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	SequenceNumber       uint32   `protobuf:"varint,8,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebSocketPacketPayload) Reset()         { *m = WebSocketPacketPayload{} }
func (m *WebSocketPacketPayload) String() string { return proto.CompactTextString(m) }
func (*WebSocketPacketPayload) ProtoMessage()    {}
func (*WebSocketPacketPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a075f58f70088c8, []int{0}
}

func (m *WebSocketPacketPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketPacketPayload.Unmarshal(m, b)
}
func (m *WebSocketPacketPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketPacketPayload.Marshal(b, m, deterministic)
}
func (m *WebSocketPacketPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketPacketPayload.Merge(m, src)
}
func (m *WebSocketPacketPayload) XXX_Size() int {
	return xxx_messageInfo_WebSocketPacketPayload.Size(m)
}
func (m *WebSocketPacketPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketPacketPayload.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketPacketPayload proto.InternalMessageInfo

func (m *WebSocketPacketPayload) GetPacketType() uint32 {
	if m != nil {
		return m.PacketType
	}
	return 0
}

func (m *WebSocketPacketPayload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WebSocketPacketPayload) GetEHost() uint32 {
	if m != nil {
		return m.EHost
	}
	return 0
}

func (m *WebSocketPacketPayload) GetEPort() uint32 {
	if m != nil {
		return m.EPort
	}
	return 0
}

func (m *WebSocketPacketPayload) GetSHost() uint32 {
	if m != nil {
		return m.SHost
	}
	return 0
}

func (m *WebSocketPacketPayload) GetSPort() uint32 {
	if m != nil {
		return m.SPort
	}
	return 0
}

func (m *WebSocketPacketPayload) GetConnectionId() []byte {
	if m != nil {
		return m.ConnectionId
	}
	return nil
}

func (m *WebSocketPacketPayload) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

type WebSocketAuthPayload struct {
	ConnectionType       uint32   `protobuf:"varint,1,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	CertificateData      []byte   `protobuf:"bytes,2,opt,name=certificate_data,json=certificateData,proto3" json:"certificate_data,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  []byte   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId             []byte   `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               []byte   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceData           []byte   `protobuf:"bytes,7,opt,name=device_data,json=deviceData,proto3" json:"device_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebSocketAuthPayload) Reset()         { *m = WebSocketAuthPayload{} }
func (m *WebSocketAuthPayload) String() string { return proto.CompactTextString(m) }
func (*WebSocketAuthPayload) ProtoMessage()    {}
func (*WebSocketAuthPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a075f58f70088c8, []int{1}
}

func (m *WebSocketAuthPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketAuthPayload.Unmarshal(m, b)
}
func (m *WebSocketAuthPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketAuthPayload.Marshal(b, m, deterministic)
}
func (m *WebSocketAuthPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketAuthPayload.Merge(m, src)
}
func (m *WebSocketAuthPayload) XXX_Size() int {
	return xxx_messageInfo_WebSocketAuthPayload.Size(m)
}
func (m *WebSocketAuthPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketAuthPayload.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketAuthPayload proto.InternalMessageInfo

func (m *WebSocketAuthPayload) GetConnectionType() uint32 {
	if m != nil {
		return m.ConnectionType
	}
	return 0
}

func (m *WebSocketAuthPayload) GetCertificateData() []byte {
	if m != nil {
		return m.CertificateData
	}
	return nil
}

func (m *WebSocketAuthPayload) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *WebSocketAuthPayload) GetUid() []byte {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *WebSocketAuthPayload) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *WebSocketAuthPayload) GetUserId() []byte {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *WebSocketAuthPayload) GetDeviceData() []byte {
	if m != nil {
		return m.DeviceData
	}
	return nil
}

func init() {
	proto.RegisterType((*WebSocketPacketPayload)(nil), "WebSocketPacketPayload")
	proto.RegisterType((*WebSocketAuthPayload)(nil), "WebSocketAuthPayload")
}

func init() {
	proto.RegisterFile("payloads.proto", fileDescriptor_3a075f58f70088c8)
}

var fileDescriptor_3a075f58f70088c8 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x53, 0xa1, 0x05, 0xc7, 0xf2, 0x27, 0x1b, 0xd4, 0x26, 0x1e, 0x24, 0x78, 0x00, 0x2f,
	0x5e, 0x7c, 0x02, 0x13, 0x0f, 0x72, 0x31, 0xa4, 0x9a, 0x78, 0x6c, 0xca, 0xee, 0x18, 0x1a, 0xb4,
	0xbb, 0xee, 0x4e, 0x4d, 0x78, 0x64, 0x9f, 0xc0, 0xab, 0xd9, 0x59, 0x90, 0x5e, 0x9a, 0x99, 0xdf,
	0x7c, 0xed, 0xf4, 0xfb, 0x06, 0x86, 0xa6, 0xdc, 0x7d, 0xe8, 0x52, 0xb9, 0x3b, 0x63, 0x35, 0xe9,
	0xd9, 0x6f, 0x04, 0x17, 0x6f, 0xb8, 0x7e, 0xd1, 0x72, 0x8b, 0xb4, 0x2a, 0xc3, 0x93, 0x15, 0xe2,
	0x1a, 0xce, 0x0c, 0x83, 0x82, 0x76, 0x06, 0xb3, 0x68, 0x1a, 0x2d, 0x06, 0x39, 0x04, 0xf4, 0xba,
	0x33, 0x28, 0x04, 0x74, 0x55, 0x49, 0x65, 0x76, 0x32, 0x8d, 0x16, 0x69, 0xce, 0xb5, 0x38, 0x87,
	0x04, 0x8b, 0x8d, 0x76, 0x94, 0x75, 0x58, 0x1f, 0xe3, 0x93, 0x76, 0x14, 0xb0, 0xd1, 0x96, 0xb2,
	0xee, 0x1e, 0xaf, 0xb4, 0x65, 0xec, 0x82, 0x3a, 0x0e, 0xd8, 0x1d, 0xd4, 0x2e, 0xa8, 0x93, 0x3d,
	0x66, 0xf5, 0x0d, 0x0c, 0xa4, 0xae, 0x6b, 0x94, 0x54, 0xe9, 0xba, 0xa8, 0x54, 0xd6, 0xe3, 0xc5,
	0xe9, 0x11, 0x2e, 0x95, 0x98, 0xc3, 0xc8, 0xe1, 0x57, 0x83, 0xb5, 0xc4, 0xa2, 0x6e, 0x3e, 0xd7,
	0x68, 0xb3, 0x3e, 0x7f, 0x64, 0x78, 0xc0, 0xcf, 0x4c, 0x67, 0x3f, 0x11, 0x4c, 0xfe, 0x9d, 0x3f,
	0x34, 0xb4, 0x39, 0xf8, 0x9e, 0xc3, 0xa8, 0xb5, 0xa6, 0xe5, 0x7d, 0x78, 0xc4, 0xec, 0xff, 0x16,
	0xc6, 0x12, 0x2d, 0x55, 0xef, 0x95, 0x2c, 0x09, 0x8b, 0x56, 0x16, 0xa3, 0x16, 0x7f, 0xf4, 0xb1,
	0x4c, 0x20, 0x26, 0xbd, 0xc5, 0x9a, 0x53, 0x49, 0xf3, 0xd0, 0x88, 0x31, 0x74, 0x9a, 0x4a, 0x71,
	0x24, 0x69, 0xee, 0x4b, 0x71, 0x05, 0xa7, 0x0a, 0xbf, 0x2b, 0x89, 0xde, 0x5e, 0xcc, 0xbc, 0x1f,
	0xc0, 0x52, 0x89, 0x4b, 0xe8, 0x35, 0x0e, 0xad, 0x1f, 0x25, 0x3c, 0x4a, 0x7c, 0xbb, 0xe4, 0x4b,
	0xed, 0xdf, 0xe2, 0x7f, 0x08, 0xb1, 0x40, 0x40, 0x7e, 0xfd, 0x3a, 0xe1, 0x63, 0xdf, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x19, 0x0c, 0xf7, 0x60, 0xfe, 0x01, 0x00, 0x00,
}
